[package]
name = "nim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.0"

[dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
